<%@ Page Title="Adicionar Tarefa" Language="C#" MasterPageFile="~/hephaestus.Master" AutoEventWireup="true" CodeBehind="task_create.aspx.cs" Inherits="hephaestus_web.task_create" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <div class="ticket-workspace task-create-page">
  <nav class="workspace-breadcrumb mb-3"><a href="tickets_listing.aspx">Tickets e tarefas</a><i class="mdi mdi-chevron-right"></i><a href="ticket_detail.aspx">—</a><i class="mdi mdi-chevron-right"></i><span>Nova tarefa</span></nav>
  <div class="d-flex flex-wrap align-items-center justify-content-between mb-4"><div class="d-flex align-items-center"><span class="page-title-icon mr-3"><i class="mdi mdi-calendar-plus"></i></span><div><h3 class="mb-1">Adicionar tarefa</h3><p class="text-muted mb-0">Planeie uma intervenção associada ao ticket —</p></div></div><a href="ticket_detail.aspx" class="btn btn-outline-light mt-3 mt-md-0"><i class="mdi mdi-arrow-left mr-1"></i> Voltar ao ticket</a></div>
  <div class="row"><div class="col-xl-8">
   <div class="card mb-4"><div class="card-body"><div class="workspace-section-heading"><span>1</span><div><h4>Ticket associado</h4><p>A tarefa ficará permanentemente relacionada com este pedido.</p></div></div><div class="parent-ticket"><span class="detail-type-icon type-sup"><i class="mdi mdi-lifebuoy"></i></span><div><strong>— · Ticket selecionado</strong><small>Dados a carregar pelo backend</small></div><span class="badge status-badge">—</span></div></div></div>
   <div class="card mb-4"><div class="card-body"><div class="workspace-section-heading"><span>2</span><div><h4>Planeamento da intervenção</h4><p>Defina o técnico responsável e um período sem conflitos de agenda.</p></div></div>
    <div class="form-group"><label for="taskTechnician">Técnico responsável <span class="text-danger">*</span></label><select id="taskTechnician" class="form-control" required><option value="">Selecione um técnico</option></select><small class="text-muted">O esquema atual guarda um técnico principal por tarefa.</small></div>
    <div class="row"><div class="col-md-6"><div class="form-group"><label for="scheduledStart">Início agendado <span class="text-danger">*</span></label><input id="scheduledStart" class="form-control" type="datetime-local" required /></div></div><div class="col-md-6"><div class="form-group"><label for="scheduledEnd">Fim agendado <span class="text-danger">*</span></label><input id="scheduledEnd" class="form-control" type="datetime-local" required /></div></div></div>
    <div id="scheduleResult" class="schedule-result d-none" role="status" aria-live="polite"></div><button id="checkAvailability" type="button" class="btn btn-outline-primary"><i class="mdi mdi-calendar-check mr-1"></i> Verificar disponibilidade</button>
   </div></div>
   <div class="card"><div class="card-body"><div class="workspace-section-heading"><span>3</span><div><h4>Informação inicial</h4><p>Dados criados automaticamente com a nova intervenção.</p></div></div><div class="task-generated-grid"><div><small>Referência</small><strong>INT — automática</strong></div><div><small>Estado inicial</small><strong><span class="badge status-badge status-open">Open</span></strong></div><div><small>Início real</small><strong>Por registar</strong></div><div><small>Fim real</small><strong>Por registar</strong></div></div><div class="workspace-note"><i class="mdi mdi-file-pdf-box"></i><p>Ao criar a tarefa, o backend deverá gerar automaticamente a respetiva Ficha de Intervenção em PDF e adicioná-la aos anexos.</p></div></div></div>
   <div class="d-flex justify-content-end mt-4"><a href="ticket_detail.aspx" class="btn btn-outline-secondary mr-2">Cancelar</a><button id="createTask" type="button" class="btn btn-success"><i class="mdi mdi-check mr-1"></i> Criar tarefa</button></div>
  </div><aside class="col-xl-4 mt-4 mt-xl-0"><div class="card sticky-summary"><div class="card-body"><h4 class="card-title"><i class="mdi mdi-clipboard-text-outline text-primary mr-2"></i>Resumo da tarefa</h4><div class="summary-reference"><small>Nova referência</small><strong>INT — automática</strong></div><dl class="ticket-summary-list"><dt>Ticket</dt><dd>—</dd><dt>Técnico</dt><dd id="summaryTechnician">Por selecionar</dd><dt>Início</dt><dd id="summaryStart">Por agendar</dd><dt>Fim</dt><dd id="summaryEnd">Por agendar</dd><dt>Estado</dt><dd><span class="badge status-badge status-open">Open</span></dd></dl><ul class="workspace-guidelines mt-4"><li><i class="mdi mdi-calendar-alert text-warning"></i><span>Não é permitido sobrepor tarefas do mesmo técnico.</span></li><li><i class="mdi mdi-lock-outline text-primary"></i><span>As datas reais serão preenchidas durante a execução e não na criação.</span></li><li><i class="mdi mdi-email-outline text-success"></i><span>A criação deverá notificar o requerente e o técnico.</span></li></ul></div></div></aside></div>
 </div>
 <div id="taskFeedback" class="ticket-feedback" role="status" aria-live="polite"></div>
 <script>
 (function(){'use strict';var technician=document.getElementById('taskTechnician'),start=document.getElementById('scheduledStart'),end=document.getElementById('scheduledEnd'),result=document.getElementById('scheduleResult'),availabilityConfirmed=false;var conflicts=[];
 function format(value){if(!value)return 'Por agendar';return new Date(value).toLocaleString('pt-PT',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}function updateSummary(){document.getElementById('summaryTechnician').textContent=technician.value?technician.options[technician.selectedIndex].text:'Por selecionar';document.getElementById('summaryStart').textContent=format(start.value);document.getElementById('summaryEnd').textContent=format(end.value);availabilityConfirmed=false;result.classList.add('d-none');}function validate(){var controls=[technician,start,end],valid=true;controls.forEach(function(c){var missing=!c.value;c.classList.toggle('is-invalid',missing);if(missing)valid=false;});if(valid&&new Date(end.value)<=new Date(start.value)){end.classList.add('is-invalid');result.className='schedule-result schedule-error';result.innerHTML='<i class="mdi mdi-alert-circle mr-1"></i>O fim agendado deve ser posterior ao início.';valid=false;}return valid;}function check(){if(!validate())return false;var requestedStart=new Date(start.value),requestedEnd=new Date(end.value),conflict=conflicts.find(function(item){return item.technician===technician.value&&requestedStart<new Date(item.end)&&requestedEnd>new Date(item.start);});result.classList.remove('d-none');if(conflict){result.className='schedule-result schedule-error';result.innerHTML='<i class="mdi mdi-calendar-remove mr-1"></i>Conflito com '+conflict.reference+'. Escolha outro período ou técnico.';availabilityConfirmed=false;return false;}result.className='schedule-result schedule-success';result.innerHTML='<i class="mdi mdi-calendar-check mr-1"></i>O técnico está disponível neste período.';availabilityConfirmed=true;return true;}[technician,start,end].forEach(function(c){c.addEventListener('change',updateSummary);});document.getElementById('checkAvailability').addEventListener('click',check);document.getElementById('createTask').addEventListener('click',function(){if(!availabilityConfirmed&&!check())return;var feedback=document.getElementById('taskFeedback');feedback.textContent='Tarefa validada. A gravação, referência INT e PDF serão ligados ao backend C#.';feedback.classList.add('show');window.setTimeout(function(){feedback.classList.remove('show');},3200);});updateSummary();}());
 </script>
</asp:Content>
