<%@ Page Title="Detalhe de Tarefa" Language="C#" MasterPageFile="~/hephaestus.Master" AutoEventWireup="true" CodeBehind="task_detail.aspx.cs" Inherits="hephaestus_web.task_detail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <div class="ticket-workspace detail-page task-detail-page">
  <nav class="workspace-breadcrumb mb-3"><a href="tickets_listing.aspx">Tickets e tarefas</a><i class="mdi mdi-chevron-right"></i><a href="ticket_detail.aspx">—</a><i class="mdi mdi-chevron-right"></i><span>—</span></nav>
  <div class="detail-hero task-detail-hero card mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-start"><div class="d-flex"><span class="detail-type-icon task-progress"><i class="mdi mdi-wrench"></i></span><div><div class="d-flex flex-wrap align-items-center mb-1"><strong class="detail-reference mr-2">—</strong><span id="taskHeroStatus" class="badge status-badge">—</span></div><h3>Tarefa não carregada</h3><p class="text-muted mb-0">Intervenção associada a <a href="ticket_detail.aspx">—</a></p></div></div><div class="detail-actions mt-3 mt-lg-0"><button id="editTask" type="button" class="btn btn-outline-light"><i class="mdi mdi-pencil mr-1"></i> Editar agenda</button><button type="button" class="btn btn-warning" data-toggle="modal" data-target="#taskStatusModal"><i class="mdi mdi-swap-horizontal mr-1"></i> Alterar estado</button><button id="registerTime" type="button" class="btn btn-primary" data-toggle="modal" data-target="#timeModal"><i class="mdi mdi-clock-check-outline mr-1"></i> Registar tempos</button></div></div></div></div>
  <div class="workspace-tabs mb-4"><a class="active" href="task_detail.aspx"><i class="mdi mdi-information-outline"></i>Detalhe</a><a href="ticket_attachments.aspx"><i class="mdi mdi-paperclip"></i>Anexos <span>2</span></a><a href="ticket_history.aspx"><i class="mdi mdi-message-text-outline"></i>Comentários / Histórico <span>5</span></a></div>
  <div class="row"><div class="col-xl-8">
   <div class="card mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="card-title mb-0">Planeamento da intervenção</h4><span id="taskEditingLabel" class="badge badge-outline-primary d-none"><i class="mdi mdi-pencil mr-1"></i>Modo de edição</span></div><div id="taskScheduleView" class="task-schedule-grid"><div><span class="task-data-icon"><i class="mdi mdi-account-hard-hat"></i></span><small>Técnico responsável</small><strong id="taskTechnicianView">—</strong><em>Localidade: —</em></div><div><span class="task-data-icon"><i class="mdi mdi-calendar-start"></i></span><small>Início agendado</small><strong id="taskStartView">—</strong><em>—</em></div><div><span class="task-data-icon"><i class="mdi mdi-calendar-end"></i></span><small>Fim agendado</small><strong id="taskEndView">—</strong><em>Duração prevista: —</em></div><div><span class="task-data-icon"><i class="mdi mdi-map-marker-outline"></i></span><small>Local da intervenção</small><strong>—</strong><em>Equipamento: —</em></div></div>
    <div id="taskScheduleEdit" class="d-none"><div class="form-group"><label for="editTaskTechnician">Técnico responsável</label><select id="editTaskTechnician" class="form-control"><option value="">Selecione um técnico</option></select></div><div class="row"><div class="col-md-6"><div class="form-group"><label for="editTaskStart">Início agendado</label><input id="editTaskStart" class="form-control" type="datetime-local"  /></div></div><div class="col-md-6"><div class="form-group"><label for="editTaskEnd">Fim agendado</label><input id="editTaskEnd" class="form-control" type="datetime-local"  /></div></div></div><div id="taskScheduleValidation" class="schedule-result d-none"></div><div class="text-right"><button id="cancelTaskEdit" type="button" class="btn btn-outline-secondary mr-2">Cancelar</button><button id="saveTaskEdit" type="button" class="btn btn-success"><i class="mdi mdi-content-save mr-1"></i> Guardar agenda</button></div></div>
   </div></div>
   <div class="card mb-4"><div class="card-body"><h4 class="card-title">Execução da tarefa</h4><div class="empty-state py-4"><i class="mdi mdi-progress-clock d-block h2"></i><div class="text-white mb-1">Sem dados de execução</div><small>O progresso será apresentado quando a tarefa for carregada.</small></div><div class="actual-time-grid"><div><small>Início real</small><strong id="actualStartView">—</strong></div><div><small>Fim real</small><strong id="actualEndView">—</strong></div><div><small>Tempo decorrido</small><strong>—</strong></div></div></div></div>
   <div class="card"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center"><div><h4 class="card-title mb-1">Ficha de Intervenção</h4><p class="text-muted small mb-0">Documento gerado automaticamente aquando da criação da tarefa.</p></div><div class="mt-3 mt-md-0"><a href="#" class="btn btn-outline-light mr-2 disabled" aria-disabled="true"><i class="mdi mdi-eye-outline mr-1"></i> Visualizar</a><button type="button" class="btn btn-primary" disabled><i class="mdi mdi-download mr-1"></i> Descarregar PDF</button></div></div><div class="intervention-file mt-3"><span class="file-tile file-pdf"><i class="mdi mdi-file-pdf-box"></i></span><div><strong>Ficha de Intervenção</strong><small>Documento a gerar pelo backend</small></div><span class="badge badge-outline-secondary">Indisponível</span></div></div></div>
  </div><aside class="col-xl-4 mt-4 mt-xl-0"><div class="card mb-4"><div class="card-body"><h4 class="card-title">Informação da tarefa</h4><dl class="detail-metadata"><dt>Referência</dt><dd class="text-primary">—</dd><dt>Ticket associado</dt><dd><a href="ticket_detail.aspx">—</a></dd><dt>Estado</dt><dd><span id="taskMetadataStatus" class="badge status-badge">—</span></dd><dt>Técnico</dt><dd>—</dd><dt>Agendada</dt><dd>—</dd><dt>Última atualização</dt><dd>—</dd></dl></div></div><div class="card"><div class="card-body"><h4 class="card-title">Ticket de origem</h4><a class="parent-ticket compact-parent" href="ticket_detail.aspx"><span class="type-icon type-sup"><i class="mdi mdi-lifebuoy"></i></span><div><strong>—</strong><small>Dados do ticket a carregar</small></div><i class="mdi mdi-chevron-right"></i></a><div class="workspace-note"><i class="mdi mdi-information-outline"></i><p>Quando todas as tarefas estiverem Closed, o ticket poderá passar para Resolved.</p></div></div></div></aside></div>
 </div>
 <div class="modal fade" id="taskStatusModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content ticket-modal"><div class="modal-header"><div><h5 class="modal-title">Alterar estado da tarefa</h5><small class="text-muted">— · Estado atual: <strong id="taskCurrentStatus">—</strong></small></div><button type="button" class="close text-white" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><label for="newTaskStatus">Novo estado</label><select id="newTaskStatus" class="form-control"><option>Open</option><option>On Hold</option><option>In Progress</option><option>Done</option><option>Closed</option></select><div class="workspace-note mt-3"><i class="mdi mdi-file-check-outline"></i><p>O estado Closed só deverá ser confirmado após anexar a Ficha de Intervenção preenchida.</p></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancelar</button><button id="confirmTaskStatus" type="button" class="btn btn-warning">Confirmar estado</button></div></div></div></div>
 <div class="modal fade" id="timeModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content ticket-modal"><div class="modal-header"><h5 class="modal-title">Registar tempos reais</h5><button type="button" class="close text-white" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><div class="form-group"><label for="actualStartInput">Início real</label><input id="actualStartInput" class="form-control" type="datetime-local"  /></div><div class="form-group mb-0"><label for="actualEndInput">Fim real</label><input id="actualEndInput" class="form-control" type="datetime-local" /></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancelar</button><button id="saveActualTimes" type="button" class="btn btn-primary">Guardar tempos</button></div></div></div></div>
 <div id="taskDetailFeedback" class="ticket-feedback" role="status" aria-live="polite"></div>
 <script>
 (function(){'use strict';var edit=document.getElementById('editTask'),view=document.getElementById('taskScheduleView'),form=document.getElementById('taskScheduleEdit'),label=document.getElementById('taskEditingLabel');function feedback(text){var el=document.getElementById('taskDetailFeedback');el.textContent=text;el.classList.add('show');setTimeout(function(){el.classList.remove('show');},2800);}function editing(active){view.classList.toggle('d-none',active);form.classList.toggle('d-none',!active);label.classList.toggle('d-none',!active);edit.innerHTML=active?'<i class="mdi mdi-close mr-1"></i> Fechar edição':'<i class="mdi mdi-pencil mr-1"></i> Editar agenda';}edit.addEventListener('click',function(){editing(form.classList.contains('d-none'));});document.getElementById('cancelTaskEdit').addEventListener('click',function(){editing(false);});document.getElementById('saveTaskEdit').addEventListener('click',function(){var start=document.getElementById('editTaskStart'),end=document.getElementById('editTaskEnd'),message=document.getElementById('taskScheduleValidation');if(!start.value||!end.value||new Date(end.value)<=new Date(start.value)){message.className='schedule-result schedule-error';message.textContent='O fim deve ser posterior ao início e não pode criar conflitos de agenda.';return;}editing(false);feedback('Agenda atualizada localmente no protótipo.');});var classes={'Open':'task-status-open','On Hold':'task-status-hold','In Progress':'task-status-progress','Done':'task-status-done','Closed':'task-status-closed'};document.getElementById('confirmTaskStatus').addEventListener('click',function(){var status=document.getElementById('newTaskStatus').value;['taskHeroStatus','taskMetadataStatus'].forEach(function(id){var badge=document.getElementById(id);Object.keys(classes).forEach(function(key){badge.classList.remove(classes[key]);});badge.classList.add(classes[status]);badge.textContent=status;});document.getElementById('taskCurrentStatus').textContent=status;$('#taskStatusModal').modal('hide');feedback('Estado da tarefa alterado para '+status+'.');});document.getElementById('saveActualTimes').addEventListener('click',function(){var start=document.getElementById('actualStartInput').value,end=document.getElementById('actualEndInput').value;if(start)document.getElementById('actualStartView').textContent=new Date(start).toLocaleString('pt-PT');if(end)document.getElementById('actualEndView').textContent=new Date(end).toLocaleString('pt-PT');$('#timeModal').modal('hide');feedback('Tempos reais atualizados localmente.');});}());
 </script>
</asp:Content>
