<%@ Page Title="Comentários e Histórico" Language="C#" MasterPageFile="~/hephaestus.Master" AutoEventWireup="true" CodeBehind="ticket_history.aspx.cs" Inherits="hephaestus_web.ticket_history" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <div class="ticket-workspace detail-page">
  <nav class="workspace-breadcrumb mb-3"><a href="tickets_listing.aspx">Tickets e tarefas</a><i class="mdi mdi-chevron-right"></i><a href="ticket_detail.aspx">—</a><i class="mdi mdi-chevron-right"></i><span>Comentários / Histórico</span></nav>
  <div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div class="d-flex align-items-center"><span class="page-title-icon mr-3"><i class="mdi mdi-message-text-outline"></i></span><div><h3 class="mb-1">Comentários e histórico</h3><p class="text-muted mb-0">— · Registo cronológico de comunicação e alterações</p></div></div><a class="btn btn-outline-light mt-3 mt-md-0" href="ticket_detail.aspx"><i class="mdi mdi-arrow-left mr-1"></i> Voltar ao detalhe</a></div>
  <div class="workspace-tabs mb-4"><a href="ticket_detail.aspx"><i class="mdi mdi-information-outline"></i>Detalhe</a><a href="ticket_attachments.aspx"><i class="mdi mdi-paperclip"></i>Anexos <span>0</span></a><a class="active" href="ticket_history.aspx"><i class="mdi mdi-message-text-outline"></i>Comentários / Histórico <span>0</span></a></div>
  <div class="row"><div class="col-xl-8"><div class="card mb-4"><div class="card-body"><h4 class="card-title">Adicionar comentário</h4><div class="comment-composer"><span class="mini-avatar"><i class="mdi mdi-account-outline"></i></span><div><textarea id="commentText" class="form-control" rows="4" placeholder="Escreva uma atualização, pergunta ou nota de diagnóstico..."></textarea><div class="d-flex flex-wrap justify-content-between align-items-center mt-3"><label class="internal-toggle"><input id="internalComment" type="checkbox" /><span></span><em>Comentário interno <small>Visível apenas para a equipa técnica</small></em></label><div><button class="btn btn-outline-secondary mr-2" type="button"><i class="mdi mdi-paperclip"></i></button><button id="addComment" class="btn btn-primary" type="button"><i class="mdi mdi-send mr-1"></i> Publicar comentário</button></div></div></div></div></div></div>
  <div class="card"><div class="card-body"><div class="history-toolbar"><h4 class="card-title mb-0">Linha temporal</h4><div class="btn-group btn-group-toggle history-filter" data-toggle="buttons"><label class="btn btn-outline-secondary active"><input type="radio" name="historyType" value="all" checked /> Tudo</label><label class="btn btn-outline-secondary"><input type="radio" name="historyType" value="comment" /> Comentários</label><label class="btn btn-outline-secondary"><input type="radio" name="historyType" value="change" /> Alterações</label></div></div><div id="timeline" class="history-timeline"><div class="empty-state"><i class="mdi mdi-history d-block h2"></i><div class="text-white mb-1">Sem atividade registada</div><small>Os comentários e alterações serão apresentados após integração com o backend.</small></div>
  </div></div></div></div>
  <aside class="col-xl-4 mt-4 mt-xl-0"><div class="card mb-4"><div class="card-body"><h4 class="card-title">Resumo da atividade</h4><div class="activity-stat-grid"><div><strong>0</strong><span>Comentários</span></div><div><strong>0</strong><span>Alterações</span></div><div><strong>0</strong><span>Participantes</span></div><div><strong>—</strong><span>Em acompanhamento</span></div></div></div></div><div class="card"><div class="card-body"><h4 class="card-title">Participantes</h4><div class="empty-state py-4"><i class="mdi mdi-account-group-outline d-block h3"></i><small>Sem participantes para apresentar.</small></div></div></div></aside></div>
 </div>
 <script>(function(){document.querySelectorAll('input[name="historyType"]').forEach(function(r){r.addEventListener('change',function(){var value=this.value;document.querySelectorAll('.history-entry').forEach(function(e){e.classList.toggle('d-none',value!=='all'&&e.dataset.kind!==value);});});});document.getElementById('addComment').addEventListener('click',function(){var box=document.getElementById('commentText');if(!box.value.trim()){box.classList.add('is-invalid');return;}window.alert('Comentário preparado. A publicação será ligada ao backend C#.');box.classList.remove('is-invalid');});}());</script>
</asp:Content>
